[supervisord]
nodaemon=false
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid

[program:tor]
command=tor
autorestart=true
startsecs=30
stderr_logfile=/var/log/tor.err.log
stdout_logfile=/var/log/tor.out.log

[program:goapp]
command=/app/AssimilateProxyGO
autorestart=true
startsecs=5
stderr_logfile=/var/log/goapp.err.log
stdout_logfile=/var/log/goapp.out.log

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
